### ISSUE TITLE
Analysis / Compositing

### ISSUE THREAD

**Issue by pdirmeyer** [nTavakoli/Assignment3#2]
You have built your composites for SOI strictly by sign (positive vs negative) using all data. It may be better to do one of the following, to get a clear signal:
1. Use the thresholds for 3 phases (including "neutral") by the standard definition (±1 standard deviation)
2. Chose more extreme ranges for SOI (a threshold larger than ±1)
3. Chose the extremes by percentages (e.g., the top and bottom 5% or 10% of all timesteps).

Each would give slightly different results - and each would have its own reason for choosing. Which makes sense to you?

**Comment by nTavakoli** [comment]
I chose the third option. I calculated 15 and 85 percentages of SOI to determine a threshold for El Nino, La Nino, and Neutral phases. The 15 % of lower and higher percentages of SOI have been considered as El Nino and La Nino, respectively. Neutral is considered between these two thresholds.
